name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/TodoList.Console/TodoList.Console.csproj

      - name: Build
        run: dotnet build src/TodoList.Console/TodoList.Console.csproj --configuration Release --no-restore
